#!/bin/bash

# SPDX-License-Identifier: GPL-2.0

if (( $# == 0 )); then
  echo "error: No arguments passed."
  echo "pkgbase is a required argument"
  exit 1
fi

PKGBASE=$1

if [[ ! -d "$PKGBASE" ]]; then
  echo "error: directory $1 does not exists"
  exit 1
fi

TMPDIR=$(mktemp -d)

function cleanup {
  rm -rf "$TMPDIR"
}

trap cleanup EXIT

REPONAME=$(basename "$PKGBASE")

# The AUR does not support a main default branch, so we have to git init with a
# master branch explictly https://bugs.archlinux.org/task/72163
git init -b master $TMPDIR
cp $PKGBASE/* $TMPDIR

pushd $TMPDIR
git remote add origin "ssh://aur@aur.archlinux.org/$REPONAME.git"
makepkg --printsrcinfo > .SRCINFO
git add .SRCINFO
git add *

git commit -m 'import from community'
git push origin master

popd
