#!/usr/bin/python

# SPDX-License-Identifier: GPL-2.0

import argparse
import sys

import requests

CMD = './db-move {} {} {}'


def main(url):
    pkgs = set()
    communitypkgs = set()
    multilibpkgs = set()

    try:
        r = requests.get(url)
    except requests.exceptions.RequestException as e:
        print(e)
        sys.exit(1)

    for pkg in r.json()['packages']:
        pkgbase = pkg['pkgbase']

        if pkg['repo'] == 'community':
            communitypkgs.add(pkgbase)
        elif pkg['repo'] == 'multilib':
            multilibpkgs.add(pkgbase)
        else:
            pkgs.add(pkgbase)

    if pkgs:
        print(CMD.format('staging', 'testing', ' '.join(pkgs)))
    if communitypkgs:
        print(CMD.format('community-staging', 'community-testing', ' '.join(communitypkgs)))
    if multilibpkgs:
        print(CMD.format('multilib-staging', 'multilib-testing', ' '.join(multilibpkgs)))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='staging dbscripts generator')
    parser.add_argument('--url', type=str, help='todo list url json endpoint', required=True)

    args = parser.parse_args()

    main(args.url)
